-- 1. STUDENT PROFILES
create table if not exists public.profiles (
    id uuid references auth.users(id)
        on delete cascade
        primary key,

    full_name text not null,

    student_number text
        unique not null,

    phone text,

    email text,

    profile_image_url text,

    created_at timestamp with time zone
        default now(),

    updated_at timestamp with time zone
        default now()
);


-- 2. ELECTRONIC CATEGORIES

create table if not exists public.electronic_categories (
    category_id bigint generated by default as identity
        primary key,

    category_name text
        unique not null,

    description text,

    created_at timestamp with time zone
        default now()
);


-- 3. ELECTRONIC ITEMS

create table if not exists public.electronic_items (
    item_id bigint generated by default as identity
        primary key,

    category_id bigint
        references public.electronic_categories(category_id)
        on delete set null,

    item_name text not null,

    brand text,

    model text,

    item_condition text,

    description text,

    created_at timestamp with time zone
        default now()
);


-- 4. MARKETPLACE LISTINGS

create table if not exists public.marketplace_listings (
    listing_id bigint generated by default as identity
        primary key,

    item_id bigint
        references public.electronic_items(item_id)
        on delete cascade,

    seller_id uuid
        references public.profiles(id)
        on delete cascade,

    listing_type text not null
        check (
            listing_type in ('Sale', 'Rent', 'Both')
        ),

    sale_price numeric(10,2),

    rental_price_per_day numeric(10,2),

    deposit_amount numeric(10,2),

    listing_status text
        default 'Available'
        check (
            listing_status in
            (
                'Available',
                'Sold',
                'Rented',
                'Reserved',
                'Inactive'
            )
        ),

    created_at timestamp with time zone
        default now()
);


-- 5. LISTING IMAGES

create table if not exists public.listing_images (
    image_id bigint generated by default as identity
        primary key,

    listing_id bigint
        references public.marketplace_listings(listing_id)
        on delete cascade,

    image_url text not null,

    is_primary boolean
        default false,

    created_at timestamp with time zone
        default now()
);


-- 6. MARKETPLACE ORDERS

create table if not exists public.marketplace_orders (
    marketplace_order_id bigint generated by default as identity
        primary key,

    buyer_id uuid
        references public.profiles(id)
        on delete set null,

    seller_id uuid
        references public.profiles(id)
        on delete set null,

    order_date timestamp with time zone
        default now(),

    total_amount numeric(10,2)
        not null
        default 0,

    order_status text
        default 'Pending'
        check (
            order_status in
            (
                'Pending',
                'Confirmed',
                'Completed',
                'Cancelled'
            )
        )
);


-- 7. MARKETPLACE ORDER ITEMS

create table if not exists public.marketplace_order_items (
    marketplace_order_item_id bigint
        generated by default as identity
        primary key,

    marketplace_order_id bigint
        references public.marketplace_orders(marketplace_order_id)
        on delete cascade,

    listing_id bigint
        references public.marketplace_listings(listing_id)
        on delete set null,

    quantity integer
        not null
        default 1
        check (quantity > 0),

    unit_price numeric(10,2)
        not null,

    subtotal numeric(10,2)
        generated always as
        (quantity * unit_price)
        stored
);


-- 8. RENTALS

create table if not exists public.rentals (
    rental_id bigint
        generated by default as identity
        primary key,

    listing_id bigint
        references public.marketplace_listings(listing_id)
        on delete set null,

    renter_id uuid
        references public.profiles(id)
        on delete set null,

    owner_id uuid
        references public.profiles(id)
        on delete set null,

    start_date date not null,

    expected_return_date date not null,

    actual_return_date date,

    rental_price_per_day numeric(10,2),

    total_rental_cost numeric(10,2),

    deposit_amount numeric(10,2),

    rental_status text
        default 'Pending'
        check (
            rental_status in
            (
                'Pending',
                'Active',
                'Returned',
                'Cancelled',
                'Late'
            )
        ),

    created_at timestamp with time zone
        default now()
);


-- 9. PAYMENTS

create table if not exists public.payments (
    payment_id bigint
        generated by default as identity
        primary key,

    marketplace_order_id bigint
        references public.marketplace_orders(marketplace_order_id)
        on delete set null,

    rental_id bigint
        references public.rentals(rental_id)
        on delete set null,

    amount numeric(10,2)
        not null,

    payment_method text
        check (
            payment_method in
            (
                'Cash',
                'Card',
                'EFT',
                'Online'
            )
        ),

    payment_status text
        default 'Pending'
        check (
            payment_status in
            (
                'Pending',
                'Successful',
                'Failed',
                'Refunded'
            )
        ),

    payment_date timestamp with time zone
        default now(),

    created_at timestamp with time zone
        default now()
);


-- 10. REVIEWS

create table if not exists public.reviews (
    review_id bigint
        generated by default as identity
        primary key,

    reviewer_id uuid
        references public.profiles(id)
        on delete cascade,

    listing_id bigint
        references public.marketplace_listings(listing_id)
        on delete cascade,

    rating integer
        not null
        check (rating between 1 and 5),

    review_comment text,

    review_date timestamp with time zone
        default now()
);


-- 11. SEARCH INDEXES

create index if not exists idx_listings_seller
on public.marketplace_listings(seller_id);

create index if not exists idx_listings_item
on public.marketplace_listings(item_id);

create index if not exists idx_items_category
on public.electronic_items(category_id);

create index if not exists idx_orders_buyer
on public.marketplace_orders(buyer_id);

create index if not exists idx_orders_seller
on public.marketplace_orders(seller_id);

create index if not exists idx_rentals_renter
on public.rentals(renter_id);


-- 12. ROW LEVEL SECURITY

alter table public.profiles
enable row level security;

alter table public.electronic_categories
enable row level security;

alter table public.electronic_items
enable row level security;

alter table public.marketplace_listings
enable row level security;

alter table public.listing_images
enable row level security;

alter table public.marketplace_orders
enable row level security;

alter table public.marketplace_order_items
enable row level security;

alter table public.rentals
enable row level security;

alter table public.payments
enable row level security;

alter table public.reviews
enable row level security;


-- 13. PROFILE POLICIES

create policy "Users can view own profile"
on public.profiles
for select
using (auth.uid() = id);

create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id);


-- 14. MARKETPLACE LISTING POLICIES

create policy "Anyone can view available listings"
on public.marketplace_listings
for select
using (listing_status = 'Available');

create policy "Users can create their own listings"
on public.marketplace_listings
for insert
with check (auth.uid() = seller_id);

create policy "Users can update their own listings"
on public.marketplace_listings
for update
using (auth.uid() = seller_id);

create policy "Users can delete their own listings"
on public.marketplace_listings
for delete
using (auth.uid() = seller_id);

-- 15. ELECTRONIC ITEMS

create policy "Anyone can view electronic items"
on public.electronic_items
for select
using (true);

create policy "Anyone can view electronic categories"
on public.electronic_categories
for select
using (true);


-- 16. LISTING IMAGES

create policy "Anyone can view listing images"
on public.listing_images
for select
using (true);


-- 17. REVIEWS

create policy "Anyone can view reviews"
on public.reviews
for select
using (true);

create policy "Logged in users can create reviews"
on public.reviews
for insert
with check (auth.uid() = reviewer_id);
